European-Unified-ID/EUID-docs

- README.md
> mods to intro readme per SW

- api/v2/getting-started/gs-account-setup.md
- api/v2/ref-info/glossary-uid.md
> Gwh apidocs 2030 euid glossary

- api/v2/ref-info/glossary-uid.md
add MD in some links in glossary
> add MD in some links in glossary

- api/v2/guides/integration-prebid.md
- api/v2/ref-info/glossary-uid.md
update GDPR notice in EUID Prebid doc
> update GDPR notice in EUID Prebid doc

- api/v2/getting-started/gs-faqs.md
- api/v2/guides/custom-publisher-integration.md
- api/v2/guides/integration-prebid.md
- api/v2/guides/publisher-client-side.md
- api/v2/ref-info/glossary-uid.md
- api/v2/sdks/client-side-identity.md
- api/v2/sdks/sdk-ref-java.md
Minor wording edits resulting from development of overview pages.
> Gwh apidocs 2076 euid audience overview pages

- api/v2/ref-info/glossary-uid.md
- api/v2/sdks/summary-sdks.md
> EUID update SDK summary page

- api/v2/guides/integration-prebid-client-side.md
> add links to Prebid demo site

- docusaurus.config.js
- src/components/HomepagePartnersSegment/index.tsx
Update the docs URL from https://github.com/European-Unified-ID/EUID-docs to https://github.com/European-Unified-ID/EUID-docs/blob/main/README.md throughout the site as per @genwhittTTD
> refactor: :recycle: update docs url to repo readme

- src/pages/request-access.tsx
- src/utils/index.ts
Marketo integration is tricky. 
Refactored the marketo init and fixing multiple form fires when clicking submit.
> feat: ♻️  Request Access + Marketo Integration

- docusaurus.config.js
- updated github URL label
- add UID2 to footer nav
> feat: :recycle: Add UID2 to footer nav

- src/pages/request-access.tsx
Switching to a EUID specific marketo form and workflow.
> feat: Update Marketo form ID

- api/v2/getting-started/gs-encryption-decryption.md
Fix broken link on encryption/decryption article.
> fix broken link

- src/components/HomepageNews/index.tsx
- AddLe Media Plus and Engage.it articles
> refactor: :recycle: Add two news articles

- api/v2/sdks/sdk-ref-csharp-dotnet.md
Updated with mods from compare with latest UID2 version, excluding sharing section.
> Gwh apidocs 2152 euid update sdk csharp

- docusaurus.config.js
- src/css/navbar.scss
Fixes margins for desktop top right nav items
> fix: 💄  theme color picker margins

- docs/endpoints/post-identity-buckets.md
- docs/endpoints/post-identity-map.md
- docs/endpoints/post-token-generate.md
- docs/endpoints/post-token-refresh.md
- docs/endpoints/post-token-validate.md
Comment: minor copy fix in all 5 endpoint docs. Plus added Docu admonition MD coding.
> copy fix in endpoint docs

- docs/guides/operator-guide-aws-marketplace.md
- docs/snippets/_private-operator-attest-failure.mdx
Add Private Operator Attestation Failure section plus incorporate other earlier updates.
> update EUID AWS guide with Attestation Failure + earlier mods

- docs/sdks/sdk-ref-cplusplus.md
minor edit to C++ guide for parity with UID2
> minor edit to C++ guide for parity with UID2

- docs/sdks/sdk-ref-java.md
- docs/sdks/sdk-ref-python.md
- Java SDK, mods to clarify functions supported.
- Java SDK, updated placeholder names to EUID.
- Python: update functionality table to remove Encrypt.
- Python, fix placement of one comment tag.
Plus update to include identity mapping.
> mods to Java SDK + couple mods to Python

- docs/getting-started/gs-faqs.md
- docs/getting-started/gs-permissions.md
- docs/guides/custom-publisher-integration.md
- docs/guides/dsp-guide.md
- docs/guides/integration-javascript-server-side.md
- docs/guides/integration-javascript.md
- docs/guides/integration-options-publisher-web.md
- docs/guides/integration-prebid-client-side.md
- docs/guides/integration-prebid-server-side.md
- docs/guides/integration-prebid.md
- docs/guides/publisher-client-side.md
- docs/guides/summary-guides.md
- docs/intro.md
- docs/overviews/overview-dsps.md
- docs/overviews/overview-publishers.md
- docs/ref-info/glossary-uid.md
- docs/sdks/sdk-ref-java.md
- docs/sdks/sdk-ref-python.md
terminology update bid stream > bidstream, global, for EUID
> terminology update bid stream > bidstream, global, for EUID

- docs/ref-info/glossary-uid.md
Updates + fresh compare re EUID glossary: 
- Add bidstream, UID, UID2.
- Mods to EUID definition, other minor edits.
> updates to EUID glossary

- docs/guides/integration-prebid-client-side.md
- docs/guides/publisher-client-side.md
- static/examples/cstg-js-sdk-example/index.html
- static/examples/cstg-prebid-example/README.md
- static/examples/cstg-prebid-example/index.html
updated links to sample apps (Prebid + JS SDK) for EUID, + updated doc links in the sample apps themselves.
> updated links to sample applications + updated doc links

- docs/getting-started/gs-faqs.md
- docs/guides/advertiser-dataprovider-guide.md
Compare+updates to advertiser/data provider guide to bring it into parity with UID2 version. Minor updates.
> EUID parity, advertiser/data provider guide

- api/v2/guides/custom-publisher-integration.md
- docs/guides/custom-publisher-integration.md
- docs/guides/dsp-guide.md
- docs/guides/summary-guides.md
- docs/intro.md
Compare+updates to custom-publisher-integration.md to bring it into parity with UID2 version. Minor updates.
> Gwh apidocs 2276 parity custom publisher integration guide

- docs/guides/dsp-guide.md
> EUID parity for DSP guide

- docs/endpoints/post-token-generate.md
- docs/endpoints/post-token-refresh.md
- docs/endpoints/post-token-validate.md
- docs/endpoints/summary-endpoints.md
- docs/getting-started/gs-auth.md
- docs/getting-started/gs-encryption-decryption.md
- docs/getting-started/gs-environments.md
- docs/getting-started/gs-faqs.md
- docs/sdks/sdk-ref-java.md
add nbsp tag in endpoint copy. Part of parity work.
> add &nbsp; in endpoint copy

- docs/getting-started/gs-account-setup.md
- docs/getting-started/gs-auth.md
- docs/getting-started/gs-credentials.md
- docs/getting-started/gs-encryption-decryption.md
- docs/getting-started/gs-normalization-encoding.md
- docs/getting-started/gs-opt-out.md
- docs/guides/advertiser-dataprovider-guide.md
- docs/guides/custom-publisher-integration.md
- docs/guides/dsp-guide.md
- docs/guides/integration-javascript-server-side.md
- docs/guides/integration-options-publisher-web.md
- docs/guides/integration-prebid-client-side.md
- docs/guides/integration-prebid-server-side.md
- docs/guides/integration-prebid.md
- docs/guides/operator-guide-aws-marketplace.md
- docs/guides/summary-guides.md
- docs/sdks/client-side-identity-v2.md
- docs/sdks/sdk-ref-cplusplus.md
- docs/sdks/sdk-ref-csharp-dotnet.md
- docs/sdks/sdk-ref-java.md
- docs/sdks/sdk-ref-python.md
remove TOC from top of file (whether commented out or not) + couple of minor fixes.
> remove TOC from top of file.

- docs/guides/integration-javascript-server-side.md
- docs/guides/integration-prebid-server-side.md
sidebar updates for client-server guides
> sidebar updates for client-server guides

- docs/ref-info/glossary-uid.md
Add links on glossary terms. + Few minor copy mods.
> mods to glossary to add links on terms

- docs/guides/operator-guide-aws-marketplace.md
Text updates. Recent content updates will be in a follow-up PR.
> minor copy edits for parity with EUID other than recent updates

- api/v2/guides/custom-publisher-integration.md
- docs/guides/custom-publisher-integration.md
- docs/guides/integration-javascript-server-side.md
- docs/guides/integration-javascript.md
- docs/guides/integration-options-publisher-web.md
- docs/guides/integration-prebid-server-side.md
- docs/guides/summary-guides.md
- docs/intro.md
- docs/overviews/overview-publishers.md
- docs/ref-info/glossary-uid.md
- docs/sdks/sdk-ref-java.md
- docs/sdks/sdk-ref-python.md
- Fix instances server-side > client-server
- Fix instances server-only > server-side
- Publisher Integration Guide, Server-Only > Publisher Integration Guide, Server-Side
- Add glossary entries re client-side, server-side, client-server, integration approach
> wording updates re client-server, server-side

- docs/guides/operator-guide-aws-marketplace.md
Add logging info. One query marked for TM.
> update to add logging info

- docs/getting-started/gs-faqs.md
clarify FAQ re not storing info, EUID, for AS.
> clarify FAQ re not storing info, EUID

- docs/guides/operator-guide-aws-marketplace.md
minor copy edit re contact email
> minor copy edit

- api/v2/endpoints/summary-endpoints.md
- docs/endpoints/post-identity-buckets.md
- docs/endpoints/post-identity-map.md
- docs/endpoints/post-token-generate.md
- docs/endpoints/post-token-refresh.md
- docs/endpoints/post-token-validate.md
- docs/endpoints/summary-endpoints.md
- docs/guides/publisher-client-side.md
Done: token/validate, token/generate
> endpoint parity updates, 2 done

- docs/overviews/overview-operators-private.md
- docs/ref-info/glossary-uid.md
- docs/ref-info/ref-operators-public-private.md
- docs/sdks/client-side-identity-v2.md
parity mods for ref-info docs -- fix typos
> parity mods for ref-info docs

- docs/intro.md
> parity mods for intro.md

- package-lock.json
> npm audit fix 1 high severity vulnerability

- src/components/HomepageNews/index.tsx
https://atlassian.thetradedesk.com/jira/browse/CORPWEB-3069
- Added 4 articles
> Quarterly Site Updates Q2 2024 - Adding Articles

- docs/intro.md
- docs/overviews/overview-dsps.md
- docs/ref-info/glossary-uid.md
- docs/ref-info/ref-operators-public-private.md
- docs/sdks/sdk-ref-java.md
add glossary term, encryption key, plus links in from other files.
> add glossary term, encryption key, plus links

- docs/endpoints/post-identity-map.md
- docs/getting-started/gs-encryption-decryption.md
- docs/guides/operator-guide-aws-marketplace.md
- docs/guides/publisher-client-side.md
- Minor mods re email examples and corresponding hashed and encoded values.
- Fix a few instances of smart quotes in code samples.
> minor mods re email examples + remove smart quotes

- docs/guides/custom-publisher-integration.md
- docs/guides/integration-javascript-server-side.md
Updates to two JS docs to remove inaccurate wording re single sign-on
Corresponds to UID2 647.
> copy updates to JS docs

- docs/sdks/sdk-ref-java.md
- docs/sdks/sdk-ref-python.md
Java SDK doc, remove mentions of phone numbers. Plus same edit and adjusted wording in Python SDK doc.
> Java SDK doc, remove mentions of phone numbers

- .github/workflows/deployPreview.yml
This script, originally copied from https://github.com/IABTechLab/uid2docs/edit/main/.github/workflows/deployPreview.yml, will allow publishing a preview to https://github.com/European-Unified-ID/euid-docs-preview
> Add deployPreview script

- docs/ref-info/ref-areas-of-coverage.md
- sidebars.js
add information about  EUID areas of coverage.
> add EUID areas of coverage

- docs/getting-started/gs-environments.md
Update environments info for EUID.
> update, environments

- docs/getting-started/gs-environments.md
Environments page, edit from SW to clarify the cloud region name.
> Environments page, edit from SW

- docs/getting-started/gs-credentials.md
To Credentials doc, add client-server. Plus minor updates.
> To Credentials doc, add client-server. Plus minor updates

- docs/guides/integration-javascript-client-side.md
- docs/guides/integration-prebid-client-side.md
Improved CSTG guide and prebid client-side guide to mention optout just like https://github.com/IABTechLab/uid2docs/pull/664
> Ported https://github.com/IABTechLab/uid2docs/pull/664 changes to EUID docs

- docs/guides/integration-options-publisher-web.md
- docs/ref-info/ref-tokens.md
- sidebars.js
New page re EUID tokens + refresh tokens
> New page re EUID tokens + refresh tokens

- docs/getting-started/gs-account-setup.md
- docs/overviews/overview-publishers.md
Address edits from NT on  Account Setup page.
> edits to Account Setup page

- docs/getting-started/gs-account-setup.md
- docs/guides/integration-options-publisher-web.md
- docs/overviews/overview-publishers.md
- docs/ref-info/ref-integration-approaches.md
- docs/ref-info/updates-doc.md
- sidebars.js
> add EUID doc updates page

- sidebars.js
Updates to SDKs summary and Endpoints summary to put them at the top level in the category.
> sidebar updates

- docs/sdks/sdk-ref-cplusplus.md
- docs/sdks/sdk-ref-csharp-dotnet.md
- docs/sdks/sdk-ref-java.md
- docs/sdks/sdk-ref-javascript-v2.md
- docs/sdks/sdk-ref-javascript.md
- docs/sdks/sdk-ref-python.md
- docs/sdks/summary-sdks.md
updates to SDK functionality tables
> Gwh apidocs 2455 03 sdk doc table minor edits

- docs/sdks/sdk-ref-python.md
python SDK, add info re /identity/buckets
> python SDK, add info re /identity/buckets

- docs/ref-info/updates-doc.md
> announce SDK iOS guide

- docs/endpoints/post-token-generate.md
- docs/endpoints/post-token-refresh.md
- docs/getting-started/gs-encryption-decryption.md
- docs/getting-started/gs-faqs.md
- docs/guides/integration-javascript-client-server.md
- docs/guides/integration-javascript-client-side.md
- docs/sdks/sdk-ref-javascript-v2.md
- docs/sdks/sdk-ref-javascript.md
- docs/snippets/_example-euid-cookie.mdx
- docs/snippets/_example-identity-generate-response.mdx
- Update ad token examples from v2/v3 to v4
- Extract reusable snippets
> Update ad token examples to v4

- docs/guides/images/resource/advertiser-flow-mermaid.md.bak
- docs/guides/images/resource/dsp-guide-flow-mermaid.md.bak
- docs/guides/images/resource/integration-javascript-client-server-mermaid.md.bak
- docs/guides/images/resource/integration-publisher-server-side-mermaid.md.bak
fix comment in Mermaid files UID2 > EUID
> fix comment in Mermaid files UID2 > EUID

- docs/ref-info/glossary-uid.md
- docs/ref-info/ref-tokens.md
- sidebars.js
Add reference article re EUID tokens and refresh tokens, plus associated mods.
> add token article + associated mods

- docs/ref-info/updates-doc.md
> announce tokens doc

- docs/ref-info/updates-doc.md
> announce Private Operator doc

- docs/ref-info/updates-doc.md
add announcement for mobile docs (9 docs).
> add announcement for mobile docs

- docs/getting-started/gs-faqs.md
- docs/guides/integration-mobile-client-server.md
- docs/ref-info/ref-tokens.md
- docs/sdks/sdk-ref-java.md
- To tokens reference article, add info re SDK function for token refresh
- Add FAQ re token refresh.
> add code examples for refresh

- docs/guides/integration-prebid-client-server.md
Prebid client-server doc, parity updates:
- update Sample Token heading per JN
- update cookie example for realistic value
> update Prebid set-cookie example

- docs/guides/integration-google-ss.md
- docs/guides/integration-options-publisher-web.md
- docs/sdks/sdk-ref-javascript.md
minor edits re sample apps, Prebid.js
> minor edits re sample apps, Prebid.js

- docs/guides/integration-google-ss.md
- docs/guides/integration-prebid-client-server.md
- docs/guides/integration-prebid-client-side.md
- In GAM SS doc, add info re updating Prebid config.
- In both Prebid docs, add an "optional" section linking back for the GAM SS steps.
> GAM/SS Prebid updates for EUID

- sidebars.js
EUID sidebar mods:
- Moved 4 items GS > ref
- Initial view, expanded Integration Guides Initial view, 
- Initial view, collapsed Endpoints section
> EUID sidebar, move some items GS > ref

- docs/guides/integration-mobile-overview.md
Fix capitalization Cocoapods > CocoaPods, EUID
> Fix capitalization Cocoapods > CocoaPods, EUID

- docs/getting-started/gs-faqs.md
- docs/intro.md
External copy edits from GM, with EP approval, for EUID
> External copy edits from GM for EUID

- docs/intro.md
- docs/sdks/summary-sdks.md
SDK functionality table, add Android. Also fix home page broken link to glossary term.
> SDK functionality table, add Android

- static/examples/cstg-js-sdk-example/index.html
- static/examples/cstg-secure-signals-example/index.html
fix Algolia link issue in sample app + fix minor spacing issue in two sample apps.
> fix Algolia link issue in sample app

- docs/sdks/sdk-ref-android.md
- docs/sdks/sdk-ref-cplusplus.md
- docs/sdks/sdk-ref-csharp-dotnet.md
- docs/sdks/sdk-ref-ios.md
- docs/sdks/sdk-ref-java.md
- docs/sdks/sdk-ref-javascript-v2.md
- docs/sdks/sdk-ref-javascript.md
- docs/sdks/sdk-ref-python.md
- docs/sdks/summary-sdks.md
SDK functionality table and description mods
> SDK functionality table and description mods

- CONTRIBUTING.md
Update Contributing.md by replacing 18.12.1 with 20.16.0
> updated node version

- docs/getting-started/gs-account-setup.md
- docs/guides/integration-options-publisher-web.md
- docs/guides/operator-guide-aws-marketplace.md
- docs/ref-info/glossary-uid.md
- docs/ref-info/ref-integration-approaches.md
- docs/ref-info/ref-server-side-token-generation.md
- docs/sdks/sdk-ref-cplusplus.md
- docs/sdks/sdk-ref-csharp-dotnet.md
- docs/sdks/summary-sdks.md
Minor edits to EUID docs for parity with UID2 docs: mostly ref-info files
> parity mods to ref-info files

- docs/ref-info/updates-doc.md
Add to doc announcements page re GMA Android doc.
> Gwh apidocs 2689 whatsnew gma android doc

- docs/ref-info/ref-tokens.md
> updates re refresh frequency

- api/v2/guides/integration-prebid.md
- docs/guides/integration-javascript-client-server.md
- docs/guides/integration-prebid.md
- docs/guides/summary-guides.md
- docs/overviews/overview-publishers.md
- docs/ref-info/ref-tokens.md
porting Prebid edits from 657 to EUID docs
> porting prebid edits from 657 to EUID docs

- docs/endpoints/post-token-generate.md
- docs/endpoints/post-token-validate.md
- docs/overviews/overview-publishers.md
parity mods, endpoints + overviews folders.
> parity mods, endpoints + overviews

- docs/intro.md
- docs/sdks/sdk-ref-android.md
- docs/sdks/sdk-ref-cplusplus.md
- docs/sdks/sdk-ref-csharp-dotnet.md
- docs/sdks/sdk-ref-ios.md
- docs/sdks/sdk-ref-java.md
- docs/sdks/sdk-ref-javascript-v2.md
- docs/sdks/sdk-ref-javascript.md
- docs/sdks/sdk-ref-python.md
- docs/sdks/summary-sdks.md
Minor parity updates on overview page, SDK docs.
> parity check on overview, some mods to remove

- docs/endpoints/post-token-generate.md
- docs/endpoints/post-token-validate.md
- docs/guides/advertiser-dataprovider-guide.md
- docs/guides/dsp-guide.md
- docs/guides/integration-google-ss.md
- docs/guides/integration-javascript-client-side.md
- docs/guides/integration-javascript.md
- docs/guides/integration-mobile-client-side.md
- docs/guides/integration-mobile-overview.md
- docs/guides/integration-options-private-operator.md
- docs/guides/integration-options-publisher-web.md
- docs/guides/integration-prebid-client-server.md
- docs/guides/integration-prebid-client-side.md
- docs/guides/integration-publisher-server-side.md
- docs/guides/mobile-plugin-gma-android.md
- docs/guides/summary-guides.md
- docs/intro.md
- docs/ref-info/glossary-uid.md
- docs/ref-info/ref-operators-public-private.md
- docs/sdks/sdk-ref-android.md
- docs/sdks/sdk-ref-ios.md
- docs/sdks/sdk-ref-java.md
- docs/sdks/sdk-ref-javascript-v2.md
Updates from parity check (excluding phone number updates) to EUID files: mostly guides, some SDKs and endpoint files.
> EUID parity updates: guides and other small mods

- docs/guides/advertiser-dataprovider-guide.md
- docs/intro.md
fix two typos from yesterday's commit
> fix two typos from yesterday's commit

- docs/guides/operator-guide-aws-marketplace.md
parity updates for AWS Private Operator doc
> parity updates for AWS Private Operator doc

- docs/endpoints/post-identity-map.md
- docs/endpoints/post-token-generate.md
- docs/endpoints/summary-endpoints.md
- docs/getting-started/gs-faqs.md
- docs/getting-started/gs-opt-out.md
- docs/guides/integration-mobile-client-side.md
- docs/ref-info/ref-server-side-token-generation.md
- docs/ref-info/ref-tokens.md
additional EUID parity mods on rev of phone number PR
> additional EUID parity mods on rev of phone number PR

- docs/guides/operator-guide-aws-marketplace.md
- docs/ref-info/glossary-uid.md
- docs/ref-info/updates-doc.md
Announce EUID phone number support + one minor AWS doc mod.
> Announce EUID phone number support

- docs/endpoints/post-identity-map.md
- docs/endpoints/post-token-generate.md
- docs/sdks/sdk-ref-java.md
- Minor mods from follow-up compare of endpoint docs.
- Minor mod to Java SDK doc.
> Endpoints minor mods

- src/components/HomepageHero/index.tsx
add phone number in copy on homepage
> add phone number in copy on homepage

- src/components/HomepageNews/index.tsx
- src/components/HomepageNews/styles.module.scss
- New Q4 press releases
- Titles to the article cards
> Feat: :sparkles: add q4 articles + titles to article cards

- docs/endpoints/post-identity-buckets.md
- docs/endpoints/post-identity-map.md
- docs/endpoints/post-optout-status.md
- docs/endpoints/post-token-generate.md
- docs/endpoints/post-token-validate.md
- docs/endpoints/summary-endpoints.md
- docs/guides/advertiser-dataprovider-guide.md
- docs/guides/dsp-guide.md
- docs/guides/integration-javascript-client-server.md
- docs/guides/integration-mobile-overview.md
- docs/guides/integration-publisher-server-side.md
- docs/guides/operator-guide-aws-marketplace.md
- docs/ref-info/glossary-uid.md
Add links in various files to content in Getting Started section and especially ref-info section: EUID.
> add links to gs and ref-info files: EUID

- docs/guides/operator-guide-aws-marketplace.md
AWS Private Operator, update Linux version
> AWS Private Operator, update Linux version

- docs/getting-started/gs-faqs.md
FAQ re testing token refresh workflow: update example to include actual values
> FAQs: update example to include values

- docusaurus.config.js
- package-lock.json
- package.json
implement zoom-in tool for images
> implement zoom-in tool for images

- docs/getting-started/gs-normalization-encoding.md
update to clarify the service doesn't normalize phone (pending rev of UID2 corresponding mods)
> update to clarify the service doesn't normalize phone

- docs/getting-started/gs-faqs.md
- docs/guides/integration-google-ss.md
- docs/guides/integration-javascript-client-server.md
- docs/guides/integration-javascript-client-side.md
- docs/guides/integration-prebid-client-side.md
- docs/guides/integration-publisher-server-side.md
- docs/ref-info/glossary-uid.md
- docs/sdks/sdk-ref-javascript.md
Mods re sample application wording.
> Gwh apidocs 2801 sample apps standardize euid

- docs/guides/integration-mobile-client-server.md
- docs/guides/integration-publisher-server-side.md
minor edit re sample application
> minor edit re sample application

- docs/guides/integration-mobile-client-server.md
To client-server mobile doc section re Prebid, add note re required version
> To mobile doc section re Prebid, add note re required version

- docs/guides/advertiser-dataprovider-guide.md
Wording mod in Advertiser/Data Provider Guide
> mod to advertiser guide

- docs/guides/integration-mobile-client-server.md
- docs/guides/integration-mobile-client-side.md
add refs to isloggingenabled in copy as workaround for Algolia search results.
> add refs to isloggingenabled in copy for Algolia (EUID)

- docs/guides/advertiser-dataprovider-guide.md
Fix EUID copy errors reported (diagram fix still to come)
> Fix EUID copy errors reported

- docs/overviews/overview-publishers.md
- package-lock.json
- package.json
- src/components/DocsBanner/index.tsx
- src/components/DocsBanner/styles.module.scss
- src/css/markdown.scss
- src/theme/DocItem/Layout/index.tsx
Reverts European-Unified-ID/EUID-docs#279
> Revert "ibg-TTD-786-banner-tables"

- package-lock.json
- package.json
- src/css/markdown.scss
- Add styles to html table headers to match markdown table headers
> ibg-TTD-786-tables

- docs/guides/integration-mobile-overview.md
Comment: In mobile integration overview, convert one table to HTML (no content mods) to utilize updated css for HTML tables.
> add HTML table with new styling

- docs/guides/integration-javascript-client-server.md
update comments re JS client-server example missing
> update comments re JS client-server example missing

- docs/guides/integration-google-ss.md
fix description for GSS sample implementation(client-server > client-side).
> fix description for GSS sample implementation

- docs/guides/integration-google-ss.md
- docs/guides/summary-guides.md
> minor updates to GSS doc

- docs/ref-info/updates-doc.md
Announcement for Advertiser/Data Provider doc updates.
Announcement for Snowflake doc, commented it.
> announcements

- docs/overviews/overview-advertisers.md
- docs/overviews/overview-data-providers.md
- docs/overviews/overview-dsps.md
- docs/overviews/overview-publishers.md
overview page banners, customize colors and icons
> overview page banners, customize colors and icons

- docs/guides/integration-advertiser-dataprovider-endpoints.md
- docs/guides/integration-advertiser-dataprovider-overview.md
- docs/guides/summary-guides.md
- docs/overviews/overview-advertisers.md
- docs/overviews/overview-data-providers.md
- docs/sdks/summary-sdks.md
Update lead-in mods for new Snowflake doc.
> Snowflake lead-in mods.

- docs/guides/integration-snowflake.md
- docs/ref-info/updates-doc.md
Snowflake doc update for Marketplace listing + add announcement.
> Snowflake doc update for Marketplace listing

- docs/guides/custom-publisher-integration.mdx
> remove outdated redirect file

- docs/endpoints/summary-endpoints.md
- docs/guides/integration-mobile-overview.md
- docs/guides/integration-options-publisher-web.md
- docs/guides/integration-prebid.md
- docs/intro.md
- docs/overviews/overview-advertisers.md
- docs/overviews/overview-data-providers.md
- docs/overviews/overview-dsps.md
- docs/overviews/overview-publishers.md
- sidebars.js
implement audience-specific sidebar for EUID: sidebar, and an additional YAML value for various files.
> implement audience-specific sidebar

- docs/guides/integration-prebid.md
- docs/ref-info/glossary-uid.md
to Glossary, add GDPR definition, plus link to it.
> to Glossary, add GDPR definition

- docs/guides/integration-snowflake.md
minor edits in EUID Snowflake docs, for consistency
> minor edits in EUID Snowflake docs, for consistency

- docs/endpoints/post-token-generate.md
- docs/endpoints/post-token-refresh.md
- docs/getting-started/gs-encryption-decryption.md
- docs/getting-started/gs-faqs.md
- docs/guides/integration-ctv-guide.md
- docs/guides/integration-google-ss.md
- docs/guides/integration-javascript-client-server.md
- docs/guides/integration-javascript-client-side.md
- docs/guides/integration-javascript.md
- docs/guides/integration-mobile-client-server.md
- docs/guides/integration-mobile-client-side.md
- docs/guides/integration-mobile-overview.md
- docs/guides/integration-prebid-client-server.md
- docs/guides/integration-prebid-client-side.md
- docs/guides/integration-prebid.md
- docs/guides/integration-publisher-server-side.md
- docs/guides/operator-guide-aws-marketplace.md
- docs/overviews/overview-publishers.md
- docs/ref-info/ref-integration-sso-providers.md
- docs/sdks/sdk-ref-javascript-v2.md
- docs/sdks/sdk-ref-javascript.md
- update snippet paths to be relative paths
- Minor heading capitalization fix re "In"
> update snippet paths to be relative paths

- sidebars.js
To sidebar, add new grouping, EUID Participants
> To sidebar, add new grouping, EUID Participants

- src/theme/DocSidebarItem/index.tsx
- src/theme/DocSidebarItem/styles.css
- Add style overrides to the sidebar nav to unify spacing between different level links
> ibg-CORPWEB-3430-nav-spacing

- docs/sdks/sdk-ref-javascript.md
Mods for version 3.10.0 changes in JS SDK Dec 2024 (preparatory to adding v4 changes)
> mods for UID2 781, JS SDK version 3.10.0 updates

- docs/guides/integration-javascript-client-side.md
- docs/sdks/sdk-ref-javascript-v2.md
- docs/sdks/sdk-ref-javascript-v3.md
- docs/sdks/sdk-ref-javascript.md
- sidebars.js
> Updates for JS SDK v4

- docs/ref-info/updates-doc.md
announce JS SDK doc, token doc
> announce JS SDK doc, token doc

- docs/ref-info/updates-doc.md
Mods to doc updates page:
- In the titles, remove New and Updated, for brevity.
- Add quarterly H2 tags to break it up.
> doc updates page mods

- docs/sdks/sdk-ref-javascript-v2.md
- docs/sdks/sdk-ref-javascript-v3.md
- docs/sdks/sdk-ref-javascript.md
JS SDK doc (3 versions), mods re opt-out
Also see one question (marked in a Git comment) line 453 in the latest doc... just checking that.
> JS SDK doc (3 versions), mods re opt-out

- docs/getting-started/gs-encryption-decryption.md
add info re timestamp validity period in the request.
> add info re timestamp validity period in the request.

- docs/getting-started/gs-account-setup.md
- docs/getting-started/gs-credentials.md
- docs/guides/integration-prebid-client-side.md
add info re separate credentials for each environment
> add info re separate credentials for each environment

- docs/guides/integration-javascript-client-server.md
- docs/intro.md
Minor edits: 1) adjust link copy, 2) remove comment.
> minor edits

- .gitignore
- README.md
- src/components/CustomTags/CustomTagsContainer.tsx
- src/components/CustomTags/CustomTagsContext.tsx
- src/components/CustomTags/CustomTagsFilterList.tsx
- src/components/CustomTags/CustomTagsFilters.tsx
- src/components/CustomTags/styles.module.scss
- src/theme/Layout/Provider/index.tsx
- tsconfig.json
Added the ability to add custom tags to any markdown page. See the README.md instructions for implementation details.
> Add custom tags behavior

- docs/ref-info/updates-doc.md
> doc updates page, apply tags

- docs/guides/integration-advertiser-dataprovider-endpoints.md
- docs/guides/integration-advertiser-dataprovider-overview.md
Add sidebar to 2 Advertiser/Data Provider files
> Add sidebar to 2 Adv/DP files

- docs/ref-info/deprecation-schedule.md
AT edit to deprecation page: move Upgrade Policy section withing Private Operator Versions section.
> AK edit to move policy section

- sidebars.js
sidebar mod to expand Endpoints
> sidebar mod to expand Endpoints

- docs/ref-info/deprecation-schedule.md
to deprecation schedule, add identity map v2
> to deprecation schedule, add identity map v2

- docs/getting-started/gs-normalization-encoding.md
Minor enhancements to normalization doc based on corresponding minor updates to PP version.
> mods to normalization doc

- docs/guides/integration-snowflake.md
EUID Snowflake doc, minor mods
> EUID Snowflake doc, minor mods

- docs/getting-started/gs-faqs.md
Add an FAQ re the Prebid value to use for the atype property, for Android/iOS SDK users.
> FAQ Prebid atype for mobile users

- docs/getting-started/gs-sharing.md
- docs/sdks/summary-sdks.md
sharing overview, remove workflow section
> sharing overview, remove workflow section
